### PR TITLE
Return RC code of command when running one-liner

### LINKED ISSUE #43: one-liner: return command RC
vmtest RC returns the number of failures. That is, in one-liner mode, 0 on success, 1 on failure.

When running in one-liner mode (or when running only one command), it can be useful to return the actual code of the command if possible.

I understand this would be diverging from the multi-runs RC but it make usage slightly easier.

Here is an example use-case.

I was bissecting a failing test in bpf selftest. That test was newly introduced and `test_progs` would return `2/ENOENT` if the test is non-existent, 0 on success, 1 on failure.
When integrating with `git bissect run`, from outside `vmtest`, the ENOENT would look like a failure, e.g vmtest would return 1. If the RC of the command was actually returned, it would be easier to handle the RC from outside of vmtest.

I don't have super strong opinion on this because it is always possible to either:
- `tail -n1` on stderr and grep for the last digit
- write the RC to a shared file between the vm and the host and reuse that from outside of vmtest.

But it would be more ergonomic if this was directly available from vmtest RC.

WDYT?

### PR DESCRIPTION
**Pull request by chantra**
If we don't even get to run the command because of some other issues, EX_UNAVAILABLE (which is kind of the catchall for "something happened") is returned instead.

When multiple targets are ran, we can't really know what to return.... in which case the old behaviour is kept, e.g return the number of failed runs.

Added test to validate the behaviour.

Fixes #43

### CODE REVIEW

**Comment by chantra** [comment]
not the most elegant solution.... feedback welcome.

File: src/ui.rs [hunk 1]
```diff
@@ -158,12 +167,16 @@ impl Ui {
 
     /// UI for a single target. Must be run on its own thread.
     ///
-    /// Returns if the target was successful or not>
-    fn target_ui(updates: Receiver<Output>, target: String, show_cmd: bool) -> bool {
+    /// Returns a TargetUiRc
+    fn target_ui(updates: Receiver<Output>, target: String, show_cmd: bool) -> TargetUiRc {
```
Comment (danobi) [inline src/ui.rs:171]: Could we return `Result<Option<i32>>` instead and avoid kinda the same thing with `TargetUiRc`?

**Review by danobi — COMMENTED** [review]
Seems like a reasonable approach to me. Just one small comment about encoding errors.

File: src/ui.rs (hunk 1 above)
Comment (chantra) [reply src/ui.rs:171]: I also thought of returning a `Result` instead. What confuses me here is that we keep on incrementing the error counter instead of returning directly. Does that mean that we actually need to let the whole state machine go through? Or could we return as soon as an error is detected (and forwarded it up the stack at the same time)?
On the other hand, it seems the error is more conveniently consume as part of the `Stage` terminal.

If we need to go through the whole loop, then probably the error will be quite generic.

Comment (danobi) [reply src/ui.rs:171]: Ah I see what you mean. This makes sense, then

File: src/ui.rs [hunk 2]
```diff
@@ -245,17 +260,21 @@ impl Ui {
...
-        for (idx, target) in self
+        let targets = self
             .vmtest
             .targets()
             .iter()
             .filter(|t| filter.is_match(&t.name))
-            .enumerate()
-        {
+            .collect::<Vec<_>>();
+        let single_cmd = targets.len() == 1;
```
[the remark this answers is not in the document]
Comment (danobi) [reply src/ui.rs:275]: The number of targets does not really give us whether or not 1-liner mode was used, right? Cuz you could have a config file with a single target. Perhaps it's better just to say "if a single target is run, then you get its return code, else you get number of failed targets"

[the remark this answers is not in the document]
Comment (chantra) [reply src/ui.rs:275]: ok, so this is what is being done right now. e.g filter happens first, then we find if there is 1 or more targets.

**Review by danobi — APPROVED** [review]

**Comment by chantra** [comment]
I have a cleanup diff I was about to submit. Let me diff this separately.
