### PR TITLE
qga: Retry the connection every second.

### LINKED ISSUE #17: qga timeout
Without the following patch, vmtest simply failed to execute guest-sync on qga socket (on my box).

```
diff --git a/src/qga.rs b/src/qga.rs
index 445d11d..55b056b 100644
--- a/src/qga.rs
+++ b/src/qga.rs
@@ -72,6 +72,9 @@ impl QgaWrapper {
         recv_req: Receiver<QgaWrapperCommand>,
         send_resp: Sender<Result<QgaWrapperCommandResp>>,
     ) {
+
+        std::thread::sleep(std::time::Duration::from_millis(1000 * 20));
+
```

### PR DESCRIPTION
**Pull request by DolceTriade**
If we connect to the QGA socket too early, the VM's QGA will never respond to us no matter how many times we write commands to it.

So, do the guest_sync first synchronously and recreate the socket each attempt until it passes. Then hand off to the thread loop.

Fixes #17

### CODE REVIEW

**Comment by DolceTriade** [comment]
I wonder if we can do away with the worker thread and just perform all the operations synchronously using the read timeout instead?

File: src/qga.rs [hunk 1]
```diff
@@ -45,6 +46,32 @@ impl QgaWrapper {
...
+                    // If we fail to connect to socket, exit this thread. The main
+                    // thread will detect a hangup and error accordingly.
+                    error!("Failed to connect QGA: {}", e);
+                    return Err(e.into());
+                }
+            };
+            qga_stream.set_read_timeout(Some(Duration::from_secs(1)))?;
+            let mut qga = Qga::from_stream(&qga_stream);
+            let sync_value = &qga_stream as *const _ as usize as i32;
+            if let Ok(_) = qga.guest_sync(sync_value) {
```
Comment (danobi) [inline src/qga.rs:71]: A little odd but I guess it works. Does the sync value even matter?

**Review by danobi — COMMENTED** [review]
this looks good to me. needs a rustfmt tho.

I think you're right -- we can kill the worker thread. I did not know about setting socket timeouts at the time. It would be cleaner to use the native timeout rather than the homegrown stuff

File: src/qga.rs (hunk 1 above)
Comment (DolceTriade) [reply src/qga.rs:71]: yeah, guest_sync will validate the sync_value and return an error if it doesn't match.

**Comment by DolceTriade** [comment]
ran `cargo fmt` and `cargo fix`

File: src/qga.rs [hunk 2]
```diff
@@ -45,6 +45,32 @@ impl QgaWrapper {
...
+        // So do the guest_sync first with a timeout to ensure that the VM Guest Agent is up.
+        let end = Instant::now() + timeout;
+        while Instant::now() < end {
+            let qga_stream = match UnixStream::connect(&sock) {
+                Ok(s) => s,
+                Err(e) => {
+                    // If we fail to connect to socket, exit this thread. The main
+                    // thread will detect a hangup and error accordingly.
+                    error!("Failed to connect QGA: {}", e);
+                    return Err(e.into());
```
Comment (danobi) [inline src/qga.rs:64]: I'm wondering if hard erroring on failure here is causing the CI failure. Maybe we want to only hard error if it's the final try before timeout

Comment (DolceTriade) [reply src/qga.rs]: Maybe...tests pass locally for me.

Comment (DolceTriade) [reply src/qga.rs]: In the two failures, the VM doesn't actually seem to reach linux based on logs. wonder why

Comment (danobi) [reply src/qga.rs]: Oh, I was suggesting there might be a race here. Previous we did a bit more work before the guest-sync. Now we do it early. It's possible we are racing?

Yeah also unclear why boot logs not coming out

Comment (danobi) [reply src/qga.rs]: The PR I just opened had its CI succeed first try. I am suspecting something in this PR is causing a new issue

Comment (DolceTriade) [reply src/qga.rs]: I can repro this issue on master...somehow. I think these tests are flaky. Will try to investigate deeper...

Comment (DolceTriade) [reply src/qga.rs]: nvm, I'm just dumb. Forgot that the tests need qemu-ga installed on the host :-/

File: src/qga.rs [hunk 3]
```diff
@@ -45,118 +30,71 @@ impl QgaWrapper {
...
+                }
             }
         }
-    }
 
-    /// Sync with qemu-ga inside guest
-    pub fn guest_sync(&self, timeout: Duration) -> Result<()> {
-        self.execute(QgaWrapperCommand::GuestSync, timeout)
-            .map(|_| ())
+        Err(anyhow!("Timed out waiting for QGA connection"))
```
Comment (danobi) [inline src/qga.rs:68]:
```suggestion
        bail!("Timed out waiting for QGA connection")
```

File: src/qga.rs [hunk 4]
```diff
@@ -45,118 +30,71 @@ impl QgaWrapper {
...
     pub fn guest_exec(
         &self,
         args: qga::guest_exec,
     ) -> Result<<qga::guest_exec as QapiCommand>::Ok> {
-        match self.execute(QgaWrapperCommand::GuestExec(args), Duration::MAX)? {
-            QgaWrapperCommandResp::GuestExec(resp) => Ok(resp),
-            _ => panic!("Impossible return"),
+        if let Err(e) = self.stream.set_read_timeout(None) {
+            warn!("Error setting socket timeout: {e}");
         }
```
Comment (danobi) [inline src/qga.rs:78]: Maybe we should set a 5s timeout for all qga calls? At least for the APIs we use, they're all async. I'd be surprised if any took seconds. Unless you've seen otherwise.

That would keep the timeout setting centralized. And remove the save/restore stuff below

File: src/qga.rs (hunk 3 above)
Comment (DolceTriade) [reply src/qga.rs]: done

File: src/qga.rs (hunk 4 above)
Comment (DolceTriade) [reply src/qga.rs]: done

**Review by danobi — APPROVED** [review]
I'll fixup the rustfmt

**Comment by DolceTriade** [comment]
I swear I run cargo fmt before pushing...
